### ISSUE TITLE
Prediction on CPU

### ISSUE THREAD

**Issue by Akashpanchal95** [experiencor/keras-yolo2#143]
I am successful to build train model on my custom dataset, and it's also good accuracy but one problem is that prediction takes a long time and when I run on GPU that it better. So Is there any technique to lightweight model (faster way to predict on CPU). 
My built model size is 250 MB and trained on Inception3.

**Comment by experiencor** [comment]
@Akashpanchal95 You may try MobileNet. I find it's better than TinyYolo and it's designed for mobile. However, it would be as good as FullYolo.

**Comment by Akashpanchal95** [comment]
@experiencor Thanks for the quick reply. I will try to train the model using MobileNet.

**Comment by Akashpanchal95** [comment]
@experiencor  Thanks for your support till date. As per your suggestion, I implemented MobileNet. However, I am receiving lot's of false positive value. So I tired inception again. and it's given me good result. Can you suggest me the way to optimize inception model in such way to run with CPU in faster manner?

**Comment by experiencor** [comment]
Hi @Akashpanchal95, I don't know a lot about network optimization for mobile applications.

**Comment by Akashpanchal95** [comment]
Hi, @experiencor Thanks for quick reply, If we have 10-hour video streaming per day and how we can process it with cost and optimization with object detection. 
Can you just guide us?
