### ISSUE TITLE
ImportError: No module named cv2

### ISSUE THREAD

**Issue by IMABUNNEH** [experiencor/keras-yolo2#230]
When running python gen_anchors.py -c config.json to create anchors I get the following:

Traceback (most recent call last):
  File "gen_anchors.py", line 5, in <module>
    from preprocessing import parse_annotation
  File "/Users/(my username)/Desktop/git_repo/keras-yolo2/preprocessing.py", line 2, in <module>
    import cv2
ImportError: No module named cv2

Any idea how to fix this?

**Comment by VamshikShetty** [comment]
pip install opencv-python

here is the link : https://pypi.python.org/pypi/opencv-python

**Comment by sonineha2191** [comment]
try 
pip uninstall opencv-python
pip install opencv-contrib-python

**Comment by 17kibr** [comment]
Still no solution i see

**Comment by brown9804** [comment]
Try out with another version of python like python3. That may it be a solution.
Like this:

python3 gen_anchors.py -c config.json

**Comment by LoopGlitch26** [comment]
ImportError: No module named cv2

tried everything. still the same error. strangely, sometimes it runs and then the next time it shows the error again

**Comment by exeptionerror** [comment]
All Possible working solution added [[Solved] ImportError: No module named cv2 Cannot find module cv2 when using OpenCV](https://flutterq.com/importerror-no-module-named-cv2-cannot-find-module-cv2-when-using-opencv/)
