### ISSUE TITLE
Train only last layer of classification and the weights of detection

### ISSUE THREAD

**Issue by bexx1963** [experiencor/keras-yolo2#236]
Is it possible to train only the weights of the last layer of the classification step and then the weights for the detection? I do not want to learn the whole Yolo-network weights?

What is the weight-file 'full_yolo_backend.h5' is good for? Are this the weights for the full yolo backend which are holding fix during training on new classes?

**Comment by experiencor** [comment]
@bexx1963 https://keras.io/getting-started/faq/#how-can-i-freeze-keras-layers

**Comment by bexx1963** [comment]
Do you recommend me freezing layers during training? Have you done it for your raccoon detection too?

**Comment by experiencor** [comment]
No. I never freeze any layers.
