### ISSUE TITLE
Adding custom class with yolo

### ISSUE THREAD

**Issue by ARNABKUMARPAN** [experiencor/keras-yolo2#241]
How to apply transfer learning in yolo? I want to detect all 80 class along with a custom class using yolo model.

**Comment by experiencor** [comment]
@ARNABKUMARPAN Just follow the readme. It includes all the details.

**Comment by ARNABKUMARPAN** [comment]
I am only getting boxes for  the custom class that I added but not getting any box for those pretrained classes

**Comment by experiencor** [comment]
@ARNABKUMARPAN Sorry I really have no clues.
