### ISSUE TITLE
Data augmentation.

### ISSUE THREAD

**Issue by saeedalahmari3** [experiencor/keras-yolo2#243]
How data augmentation is done using (imgaug) for both annotation and original image? For instance, in blood detection example. I saw that annotation is in xml files. I don't know how augmentation is done in this case?

**Comment by experiencor** [comment]
@saeedalahmari3 You should see processing.py.

**Comment by chandan53** [comment]
Does data augmentation used in processing.py incorporate augmentation of bounding box?.
