### ISSUE TITLE
Some code problems with frontend.py

### ISSUE THREAD

**Issue by LBAWMY** [experiencor/keras-yolo2#247]
What does the line 190 do?
class_mask = y_true[..., 4] * tf.gather(self.class_wt, true_box_class) * self.class_scale  
Besides, I read the help doc about tf.gather(params,indices,), and it said the indices should be 0-D or1-D，and I test it in tensorflow, but I still didn't get it.

**Comment by experiencor** [comment]
it assigns different weights to different classes
