### ISSUE TITLE
Variable Image size as Input to train own dataset.

### ISSUE THREAD

**Issue by R1234A** [experiencor/keras-yolo2#251]
I am using "keras-yolo2" for my dataset in which the image size is variable means 1280*720 px. I want to ask, in the **config.json** file the **input_size** have only one dimension. So how can I give two dimensions there??

Can I give **None** in **input_size**?? So, that it can automatically takes my input image size??

Please reply asap.

**Comment by experiencor** [comment]
Nope. Variable input size is not currently implemented in this repo of mine. Try keras-yolo3 instead.

**Comment by ShilpaSangappa** [comment]
Does that mean pascal VOC dataset cannot be used for training, as the images in it are of different sizes?

**Comment by 2016JTM2091** [comment]
@experiencor  Do I need to resize every image before annotation? I'm bit confuse in this regard as i trained the model using my own data set and no box was detected. Please help me with the 'Input Size' variable. Thanks in advance.
