### ISSUE TITLE
utilize the  mobilenet  as backbone?

### ISSUE THREAD

**Issue by XiongLianga** [experiencor/keras-yolo2#252]
The input_size of mobilenet is (224,224,3), but the input_size of YOLOV2 is (416,416,3)。Does the model work well?

**Comment by experiencor** [comment]
The bigger the better.

**Comment by XiongLianga** [comment]
But it exist a problem，I use the mobilenet in keras，and  set the input_shape as （512，512，3），keras throw me a error that the input_shape should be （224，224，3）and some smaller input_shape. How can I solve the issue？thank you

**Comment by experiencor** [comment]
I use the mobilenet code from Keras. It may have this limitation but I think it's no problem at all.

**Comment by XiongLianga** [comment]
aha，when you load the imagenet weights of Mobilenet from keras, and set the input_shape to (512,512,3),  Keras don't throw a error?
