### ISSUE TITLE
Which part of the code converts .xml annotations(xmin,xmax,ymin,ymax) to the required format(x,y,w,h)?

### ISSUE THREAD

**Issue by ManjeeraJagiri** [experiencor/keras-yolo2#273]
Hi,

We provide .xml annotations for each image where xmin.xmax,ymin,ymax are the BB dimensions of each object. I am wondering where in the code are these converted to coordinates relative to the grid cells i.e (13,13,5,6) ? (Assuming I am using 5 anchor boxes and 1 class).
 Is it at the below line?
**train_batch = BatchGenerator(train_imgs, generator_config, norm=normalize)**

**Comment by ZacharyForrest** [comment]
check in preprocessing.py

**Comment by ManjeeraJagiri** [comment]
Hi,

I couldn't really understand the BatchGenerator code in preprocessing.py. Any way to get a gist of it?

**Comment by ManjeeraJagiri** [comment]
I got it now! Thanks.
