### ISSUE TITLE
Red blood Cell Detection Annotation File issue

### ISSUE THREAD

**Issue by VinodPathak** [experiencor/keras-yolo2#283]
I found an issue with the Red blood Cell annotation file. Please make sure the **folder name** in annotation file(xml files) has name as  e.g. "BloodImage_0000.jpg". Earlier it was just "BloodImage_0000". This is for every xml file. Please correct me if I am wrong.

**Comment by yumna4** [comment]
Go to preprocessing.py and change this line (line 22):

img['filename'] = img_dir + elem.text

to 

img['filename'] = img_dir + elem.text +".jpg"
