### ISSUE TITLE
No bounding box!!

### ISSUE THREAD

**Issue by LeVan146** [experiencor/keras-yolo2#290]
Hi guys, after try Blood Cell Detection, I train with 100 epochs, i think my model good but when there is no bounding box in predict step. This is my code. Can you help me, please? :'(

[examples.zip](https://github.com/experiencor/keras-yolo2/files/2014227/examples.zip)

**Comment by zmlim** [comment]
@LeVan146 hi, did you managed to solve it?

**Comment by LeVan146** [comment]
Hi Zmlim, sorry for the late reply, I think you should visualize that
bounding box before feed it to model, I remember that I fed wrong
coordination into my model.
My pleasure to help you.

Best,
Van Le
