### ISSUE TITLE
generate anchors with my dataset

### ISSUE THREAD

**Issue by frasab** [experiencor/keras-yolo2#294]
Hi people!
I'm writing again for a new problem :)
I'm trying to train the net with my dataset. So, in order to generate anchors, I've created my annotations for images and setting the config.json file (input_size now is 100).
My problem is that when I start the gen_anchors script, the output is:

> iteration 2: dists = nan
iteration 3: dists = nan
iteration 4: dists = nan
iteration 5: dists = nan

So, it never ends!
Can you suggest me anything in order to resolve it?
Thank you!

**Comment by rodrigo2019** [comment]
try to use input_size multiple of 32.
With input_size less than 160 I got really bad predictions, to fix this I created a new model with less maxPooling layers in order to create a bigger grid in the yolo ouyput.

**Comment by frasab** [comment]
Thank you very much!
