### ISSUE TITLE
Blood Cell annotations filename are missing the file extension

### ISSUE THREAD

**Issue by tamersalama** [experiencor/keras-yolo2#315]
Blood cells annotations filenames (withing each of the BloodImage_*.xml files is missing the filename extension (.jpg) in the filename tag.

Cannot find /rbc/train_image/BloodImage_00289 
...
StopIteration: 'NoneType' object has no attribute 'shape'

**Comment by tamersalama** [comment]
Duplicate of #283

**Comment by yumna4** [comment]
Go to preprocessing.py and change this line (line 22):

img['filename'] = img_dir + elem.text

to 

img['filename'] = img_dir + elem.text +".jpg"
