### ISSUE TITLE
Parse Error 

### ISSUE THREAD

**Issue by SemabAli** [experiencor/keras-yolo2#328]
File "<string>", line unknown
ParseError: syntax error: line 1, column 0

![image](https://user-images.githubusercontent.com/30036324/42734795-3cddcbd0-8863-11e8-8da4-4beac53033e4.png)
![capture](https://user-images.githubusercontent.com/30036324/42734804-4d32e15a-8863-11e8-91d2-cfaf19f428aa.PNG)

**Comment by kdohi** [comment]
I know this is late but do you know how you fixed this problems?
