### ISSUE TITLE
cannot import name 'parse_annotation' and 'WeightReader'

### ISSUE THREAD

**Issue by Yufeng4024** [experiencor/keras-yolo2#333]
I run the first Jupyter Notebook cell in Python 3.6 and get the two errors:

cannot import name 'parse_annotation',
and cannot import name 'WeightReader'

Could you direct me to the solution?

**Comment by jorgeMariano** [comment]
I think, you need import the files utils.py and preprocessing.py, to load those functions.

**Comment by Yufeng4024** [comment]
Thx.

**Comment by wangwei420625** [comment]
I also encountered the same problem, how should I solve it?
![image](https://user-images.githubusercontent.com/31655266/58714072-8d759e80-83f6-11e9-88a9-53958e024239.png)
