### ISSUE TITLE
tb_counter  = len([log for log in os.listdir(os.path.expanduser('~/logs/')) if 'coco_' in log]) + 1

### ISSUE THREAD

**Issue by Yufeng4024** [experiencor/keras-yolo2#337]
Could someone explain what the above code mean in the Python code? I got an FileNotFoundError:
[WinError 3] The system cannot find the path specified: 'C:\\Users\\Yufeng2/logs/'

**Comment by rodrigo2019** [comment]
it count how many directories with "coco_1" prefix in the name, this prevent to overwrite the logs from older trainings.

**Comment by letilessa** [comment]
You need to create a folder named logs to save the log files.

**Comment by Yufeng4024** [comment]
Thx.
