### ISSUE TITLE
Full YOLO pre-trained weights missing?

### ISSUE THREAD

**Issue by alvin319** [experiencor/keras-yolo2#350]
I'm currently following the [page](https://1drv.ms/f/s!ApLdDEW3ut5fec2OzK4S4RpT-SU) and I couldn't find the full YOLO pre-trained weights?

**Comment by bkanaki** [comment]
Those are just the backends. Do you want backend or full network weights. You can load full weights from the original darknet framework using this work.

**Comment by alvin319** [comment]
Thanks for the reply! I wanted to download the backend weights.

**Comment by bkanaki** [comment]
Here: https://github.com/rodrigo2019/keras-yolo2/releases/tag/pre-trained-weights

Thank him.

**Comment by guysoft** [comment]
I am getting from that repo:

```
Loading pre-trained weights in /home/ubuntu/machine_learning/keras-yolo2-rodrigo2019/full_yolo_backend.h5
Traceback (most recent call last):
  File "./train.py", line 137, in <module>
    _main_(args)
  File "./train.py", line 110, in _main_
    yolo.load_weights(config['train']['pretrained_weights'])
  File "/home/ubuntu/machine_learning/keras-yolo2-rodrigo2019/frontend.py", line 241, in load_weights
    self.model.load_weights(weight_path)
  File "/usr/local/lib/python3.6/dist-packages/keras/engine/network.py", line 1166, in load_weights
    f, self.layers, reshape=reshape)
  File "/usr/local/lib/python3.6/dist-packages/keras/engine/saving.py", line 1030, in load_weights_from_hdf5_group
    str(len(filtered_layers)) + ' layers.')
ValueError: You are trying to load a weight file containing 44 layers into a model with 2 layers.
```

@rodrigo2019 perhaps you can either explain why the weights don't match to your current maser, or open the issues feature in your repo?

**Comment by rodrigo2019** [comment]
Also I do not recommend to use these backend weights, in all my tests using these weights I got worst results

**Comment by guysoft** [comment]
Thanks!
Ok understood now. 

Also managing to run the raccoon example now. Loading the backend worked, will see how it handles a fresh model training and will update.

I will note I like @rodrigo2019 repo better, there are small quirks that make life easier.

**Comment by guysoft** [comment]
@rodrigo2019 Another question if I already caught you here:
In your fork there is a file ``train_classification.py``. What is this? Does it train the network differently?

**Comment by rodrigo2019** [comment]
the ideia of this script is about to train the backend weights using a classification network. But again, in all my tests using any kind of pre trained weights for the backend I got worst results.
