### ISSUE TITLE
Another question on pretrained weights

### ISSUE THREAD

**Issue by clw5180** [experiencor/keras-yolo2#396]
Dear @experiencor and ladys and gentlemen,

I've a question regarding the 'pretrained weights'. If I have trained a model for 40 epoches and saved the best to xxx.h5 model，if I want to continue using this model to train and find whether the mAP can raise more, can I just write 'xxx.h5' to the item 'pretrained_weights' in the config.json? Will the parameters of xxx.h5 loaded in my new training model? Thanks a lot.

**Comment by jzx-gooner** [comment]
YES
