### ISSUE TITLE
How to run on GPU

### ISSUE THREAD

**Issue by harshitazilen** [experiencor/keras-yolo2#416]
I tried configuring below parameters but it still does not use GPU. Please guide:
```
os.environ["CUDA_DEVICE_ORDER"] = "PCI:1:0:0"
os.environ["CUDA_VISIBLE_DEVICES"] = "0"
```

Thanks

**Comment by rodrigo2019** [comment]
if you installed tensorflow correctly, it will use GPU by default

**Comment by look4pritam** [comment]
Install cuda 10
Install cudnn for cuda-10
Install tensorflow- GPU.
Then it will work.

**Comment by harshitazilen** [comment]
Thanks. I tried by creating new virtual environment and re-configured everything and it is working now.
